[toolchain]

[build]
sh = ["bash", "-c"]

[features]
resolution = true
skip-lint = false

[programs.devnet]
privatepoker = "7qRu72wJ5AGcXkqnwXoNtkWt3Z6ZaJoyTQsEc5gzzkqK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=f3417b56-61ad-4ba8-b0f9-3695ea859a58"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
